sudo: required
dist: bionic
os:
  - linux
  - osx

env:
  - LISP=sbcl-bin
  - LISP=ccl-bin

matrix:
  include:
    - language: nix
      env:
      script: nix-build default.nix && echo -shcl-run-tests | ./result/bin/shcl
      install: true

install:
  - ./ci/install

script:
  - make LISP='ros -s cffi-grovel run --'
  - echo -shcl-run-tests | ./run-shcl
